name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install dpkg

      - name: Build deb package
        run: make deb

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload deb asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./com.gamesofts.ios.adblock.deb
          asset_name: com.gamesofts.ios.adblock.deb
          asset_content_type: application/vnd.debian.binary-package
